# Generated by Django 2.2 on 2019-04-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('COM', 'Comedy'), ('CRI', 'Crime and Ganster'), ('DRA', 'Drama'), ('HOR,', 'Horror'), ('SCI', 'Sceience Fiction')], max_length=3)),
                ('director', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dr.Director')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
